services:
  postgres:
    image: postgres:latest
    container_name: tasker
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - init:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_tasker
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  data:
  init:
  pgadmin-data:

