DELETE  http://localhost:3000/todos/16 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI4NzI1MDQ0LCJleHAiOjE3Mjg3Mjg2NDR9.m_3CwaLqgOJzLMTJ89skrzUJSckksrkw0NZQ-Q4CwYU
