POST http://localhost:3000/todos/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzI4NDc4MDU3LCJleHAiOjE3Mjg0ODE2NTd9.eBaORY5XsBuVhVWDNf7HavX8i-IIEPV5oLCdDhWTv0w

{
	"task": "auth task test"
}