DELETE  http://localhost:3005/todos/19 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3NTQzODQ0LCJleHAiOjE3Mzc1NDc0NDR9.ZQAmqjHyXBa-qkW7KJyCU7ciBm79cmURCw5nEV5M4dU
